[package]
name = "mem-isolate"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
jemallocator = "0.5.4"
libc = "0.2.170"
memory-stats = "1.2.0"
serde = "1.0.218"
serde_derive = "1.0.218"
